### ISSUE TITLE
이미지 처리 문제

### ISSUE THREAD

**Issue by letsjo** [letsjo/exercise-match#89]
- 문제 원인
게시글 작성 페이지 내에서 user가 입력한 내용을 Back-end로 전달해야하는데 입력받은 text와 file을 동시에 처리해서 넘기는데에 어려움.

- 해결 방안
1안) Front-end 에서 fire-store에 이미지 업로드 후 img url을 받아 Back-end 서버로 전송 후 db에 저장.
2안) Back-end 서버로 이미지와 텍스트를 한 번에 전송 후 Back-end에서 이미지 처리 후 url을 db에 저장.

- 결론
데이터 관리는 Back-end쪽에서 맡아 진행하는편이 옳다고 생각하여, 2안으로 결정.
Front-end 측에서 이미지를 저장하게 되면 게시물을 삭제할 때 내용과 이미지를 동시에 삭제할 때 어려움이 있을 것이라 판단.

**Comment by jjjjjeongwon** [comment]
complete
